apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: andy-evaluate-policy-test
on:
  workflow_dispatch:
    inputs:
      critical:
        type: number
        default: 0
      high:
        type: number
        default: 0
      medium:
        type: number
        default: 0
      low:
        type: number
        default: 0  
      policy:
        type: string
        default: ""
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  check:
    steps:
      - name: Build a test policy subject
        uses: docker://alpine:latest
        shell: sh
        run: |
          TOTAL=$(( ${{ inputs.critical }} + ${{ inputs.high }} + ${{ inputs.medium }} + ${{ inputs.low }} ))
          cat > /cloudbees/workspace/test-input.json << EOF
          [{
            "type": "vulnerability_scan",
            "data": {
              "summary": {
                "by_severity": {
                  "total": ${TOTAL},
                  "critical": ${{ inputs.critical }},
                  "high": ${{ inputs.high }},
                  "medium": ${{ inputs.medium }},
                  "low": ${{ inputs.low }}
                }
              }
            },
            "findings": [
              {
                "code": "CWE-22",
                "severity": "MEDIUM",
                "location": "/zip_extract.go#L13"
              },
              {
                "code": "CWE-703",
                "severity": "LOW",
                "location": "/main.go#L31"
              }
            ]  
          }]
          EOF
      - name: Print test input
        uses: docker://alpine:latest
        shell: sh
        run: |
          cat /cloudbees/workspace/test-input.json
      - id: check-vulnerabilities
        name: Check vulnerabilities
        uses: cloudbees-io/policy-check
        with:
          policy: ${{ inputs.policy }}
          input-file: /cloudbees/workspace/test-input.json
