apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-workflow-exit-check
on:
  workflow_dispatch:
jobs:
  scan-job:
    steps:
      - name: Run step
        uses: docker://alpine:3.18
        run: echo "scan-job running"

      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2
        
      - name: Run gitleaks Scan
        id: gitleaks-step
        uses: cloudbees-io/gitleaks-plugin@v1

  independent-job:
    needs:
      - scan-job
    steps:
      - name: Run step
        uses: docker://alpine:3.18
        run: echo "independent-job running"
  post-scan-job:
    needs:
      - independent-job
    steps:
      - name: Run step
        uses: docker://alpine:3.18
        run: echo "post-scan-job running"
