name: sonarqube-update-test
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on:
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  sonar-scan:
    steps:        
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v2

      - name: Setup sonarqube explicit scanner with community edition
        uses: cloudbees-io/sonarqube-plugin@CBP-41936
        with:
          url: 'https://cbsonarqube.saas-preprod.beescloud.com'
          username: ${{ secrets.CB_SONARQUBE_USERNAME }}
          password: ${{ secrets.CB_SONARQUBE_PASSWORD }}
          
