apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: walk-fail-test
on:
  workflow_dispatch: {}
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  scan-and-evaluate:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2

      - name: Run Gosec Scan
        id: gosec-step
        uses: cloudbees-io/gosec-plugin@CBP-40852 # was v1

      - id: print-gosec-outputs
        name: Print gosec outputs
        uses: docker://alpine:latest
        run: |
          echo "Gosec outputs:"
          echo "Critical: ${{ steps.gosec-step.outputs.critical-count }}"
          echo "Very high: ${{ steps.gosec-step.outputs.very-high-count }}"
          echo "High: ${{ steps.gosec-step.outputs.high-count }}"
          echo "Medium: ${{ steps.gosec-step.outputs.medium-count }}"
          echo "Low: ${{ steps.gosec-step.outputs.low-count }}"
          echo "Policy Subject: ${{ steps.gosec-step.outputs.policy-subject }}"

      # temporry transform, {} -> []
      # - id: wrap-policy-subject                                                                                                                                                                                                                                                                                                                           
      #   name: Wrap policy subject as array                                                                                                                                                                                                                                                                                                                
      #   uses: docker://alpine:latest                                                                                                                                                                                                                                                                                                                      
      #   run: |                                                                                                                                                                                                                                                                                                                                            
      #       apk add --no-cache jq                                                                                                                                                                                                                                                                                                                           
      #       echo '${{ steps.gosec-step.outputs.policy-subject }}' | jq -c '[.]' > /cloudbees/workspace/policy-input.json    
      #       echo '${{ steps.gosec-step.outputs.policy-subject }}' | jq -c '[.]'   

      # policy: crit lte 2 -> block
      - name: check-vulnerabilities
        uses: cloudbees-io/policy-check@main
        with:
          policy: cf78ccd6-b125-4378-ab1f-078ce6fe8d1d
          # input-file: /cloudbees/workspace/policy-input.json
          input-data: ${{ steps.gosec-step.outputs.policy-subject }}
