name: approval-test
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  scan-and-evaluate:
   # outputs:
   #   policy-subject: ${{ steps.gosec-step.outputs.policy-subject }}
    steps:
        - name: checkout-source-code
          id: getscm
          uses: cloudbees-io/checkout@v1
        
        - id: gosec-step
          uses: cloudbees-io/gosec-plugin@v2

        - id: print-gosec-outputs
          name: Print gosec outputs
          uses: docker://alpine:latest
          run: |
            echo "Gosec outputs:"
            echo "Critical: ${{ steps.gosec-step.outputs.critical-count }}"
            echo "Very high: ${{ steps.gosec-step.outputs.very-high-count }}"
            echo "High: ${{ steps.gosec-step.outputs.high-count }}"
            echo "Medium: ${{ steps.gosec-step.outputs.medium-count }}"
            echo "Low: ${{ steps.gosec-step.outputs.low-count }}"
            echo "Policy Subject: ${{ steps.gosec-step.outputs.policy-subject }}"
  #policy-evaluation:
  #  uses: cloudbees-io/policy-utils/evaluate-policy/workflow.yml@v0.1
  #  needs:
  #    - scan-and-evaluate
  #  with:
  #    policy-id: 9517fa03-035b-411c-a8d1-bafb4345697f
  #    input-data: ${{ needs.scan-and-evaluate.outputs.policy-subject }}